/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_seujorgenochurras_command_cli_utils_ansi_LoadingAnimation */

#ifndef _Included_io_github_seujorgenochurras_command_cli_utils_ansi_LoadingAnimation
#define _Included_io_github_seujorgenochurras_command_cli_utils_ansi_LoadingAnimation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_seujorgenochurras_command_cli_utils_ansi_LoadingAnimation
 * Method:    animateLoading
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_seujorgenochurras_command_cli_utils_ansi_LoadingAnimation_animateLoading
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
